#!/usr/bin/env bash
# sync-rules.sh — generate tool-specific rule adapters from skills/ source of truth
#
# Produces:
#   .cursor/rules/<skill>.mdc   Cursor rule files (alwaysApply or glob-triggered)
#   .windsurfrules              Windsurf flat-file rules (coding standards only)
#
# Usage:
#   bash scripts/sync-rules.sh          # regenerate all
#   bash scripts/sync-rules.sh --dry    # preview only

set -euo pipefail

SKILLS_DIR="skills"
CURSOR_DIR=".cursor/rules"
WINDSURFRULES=".windsurfrules"
DRY_RUN=false

[[ "${1:-}" == "--dry" ]] && DRY_RUN=true

write_file() {
  local path="$1"
  local content="$2"
  if $DRY_RUN; then
    echo "── $path ──────────────────────────────"
    echo "$content" | head -20
    echo "..."
  else
    echo "$content" > "$path"
    echo "  wrote $path"
  fi
}

# ---------------------------------------------------------------------------
# Skill → Cursor MDC mapping
# Each entry: "skill-name|globs|alwaysApply"
# globs="" means alwaysApply governs; globs="**/*.kt" means file-triggered
# ---------------------------------------------------------------------------
declare -A CURSOR_GLOBS=(
  [new-feature]=""
  [compose-component]="**/*.kt"
  [code-review]=""
  [refactor-kotlin]="**/*.kt"
  [coroutine-flow]="**/*.kt"
  [architecture-audit]=""
  [debug-performance]="**/*.kt"
  [write-tests]="**/*Test*.kt,**/*Spec*.kt"
  [gradle]="**/*.gradle.kts,**/libs.versions.toml"
  [github-actions-android]="**/.github/workflows/*.yml,**/.github/workflows/*.yaml"
  [adb]=""
  [auto-mobile]=""
  [figma-verify]=""
  [figma-sync]=""
)

declare -A CURSOR_ALWAYS_APPLY=(
  [new-feature]=false
  [compose-component]=true
  [code-review]=false
  [refactor-kotlin]=true
  [coroutine-flow]=true
  [architecture-audit]=false
  [debug-performance]=false
  [write-tests]=false
  [gradle]=true
  [github-actions-android]=true
  [adb]=false
  [auto-mobile]=false
  [figma-verify]=false
  [figma-sync]=false
)

# ---------------------------------------------------------------------------
# Generate .cursor/rules/<skill>.mdc
# ---------------------------------------------------------------------------
echo "Generating .cursor/rules/ from ${SKILLS_DIR}/ ..."

for skill_file in "$SKILLS_DIR"/*.md; do
  skill_name=$(basename "$skill_file" .md)

  # Extract frontmatter description
  description=$(awk '/^description:/{sub(/^description: /,""); print; exit}' "$skill_file")

  globs="${CURSOR_GLOBS[$skill_name]:-}"
  always_apply="${CURSOR_ALWAYS_APPLY[$skill_name]:-false}"

  # Build frontmatter
  frontmatter="---"$'\n'"description: ${description}"
  [[ -n "$globs" ]] && frontmatter+=$'\n'"globs: ${globs}"
  frontmatter+=$'\n'"alwaysApply: ${always_apply}"
  frontmatter+=$'\n'"---"

  # Strip YAML front matter + "When the user runs /X" dispatch line from source,
  # leaving only the actionable rule content
  body=$(awk '
    /^---$/ { if (fm<2) { fm++; next } }
    fm==2 && /^When the user runs / { next }
    fm==2 { print }
  ' "$skill_file")

  content="${frontmatter}"$'\n\n'"${body}"

  write_file "${CURSOR_DIR}/${skill_name}.mdc" "$content"
done

# Always-on base standards rule (sourced from CLAUDE.md coding standards)
standards_body=$(awk '
  /^## Coding Standards/ { found=1 }
  found { print }
  /^## Key References/ { exit }
' CLAUDE.md)

base_rule="---
description: Android AI base coding standards — enforced on every file
alwaysApply: true
---

${standards_body}"

write_file "${CURSOR_DIR}/000-base-standards.mdc" "$base_rule"

# ---------------------------------------------------------------------------
# Generate .windsurfrules (flat markdown, Windsurf reads this like .cursorrules)
# Windsurf supports a single flat file — concatenate standards + key skills
# ---------------------------------------------------------------------------
echo "Generating $WINDSURFRULES ..."

windsurf_header="# Android AI — Coding Standards
# Auto-generated by scripts/sync-rules.sh — do not edit directly
# Source of truth: skills/ and CLAUDE.md
"

# Pull coding standards from CLAUDE.md
windsurf_standards=$(awk '
  /^## Coding Standards/ { found=1 }
  found { print }
  /^## Key References/ { exit }
' CLAUDE.md)

# Pull body content from highest-value always-on skills
always_on_skills=("compose-component" "refactor-kotlin" "coroutine-flow" "gradle" "github-actions-android")

windsurf_skills=""
for skill in "${always_on_skills[@]}"; do
  skill_file="${SKILLS_DIR}/${skill}.md"
  [[ -f "$skill_file" ]] || continue
  skill_body=$(awk '
    /^---$/ { if (fm<2) { fm++; next } }
    fm==2 && /^When the user runs / { next }
    fm==2 { print }
  ' "$skill_file")
  windsurf_skills+=$'\n\n---\n\n'"${skill_body}"
done

write_file "$WINDSURFRULES" "${windsurf_header}${windsurf_standards}${windsurf_skills}"

# ---------------------------------------------------------------------------
echo ""
echo "Done. Tool-specific files generated:"
echo "  .cursor/rules/  (${#CURSOR_GLOBS[@]} skills + 1 base standards rule)"
echo "  .windsurfrules  (coding standards + 5 always-on skills)"
echo ""
echo "Codex: AGENTS.md already serves as the Codex AGENTS.md — no separate generation needed."
echo ""
echo "To regenerate after editing a skill:"
echo "  bash scripts/sync-rules.sh"
echo ""
echo "Note: claude/agents, claude/skills, claude/hooks → ../agents, ../skills, ../hooks  (root is source of truth)"
